In [1]:
## IMPORTS 
import evotoon
from data_classes import CatParam, IntParam, FloatParam


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#import seaborn as sns#

import random
import warnings
warnings.filterwarnings("ignore")

In [2]:
## MAKE SEED
SEED = evotoon.make_seed(765)
separator = "--------------------------------------------------------"

In [3]:
optimal_solutions = {
	"a280" : 2579,
	"ali535" : 202339,
	"att48" : 10628,
	"att532" : 27686,
	"bayg29" : 1610,
	"bays29" : 2020,
	"berlin52" : 7542,
	"bier127" : 118282,
	"brazil58" : 25395,
	"brd14051" : 469385,
	"brg180" : 1950,
	"burma14" : 3323,
	"ch130" : 6110,
	"ch150" : 6528,
	"d198" : 15780,
	"d493" : 35002,
	"d657" : 48912,
	"d1291" : 50801,
	"d1655" : 62128,
	"d2103" : 80450,
	"d15112" : 1573084,
	"d18512" : 645238,
	"dantzig42" : 699,
	"dsj1000" : 18659688, 
	"dsj1000" : 18660188,
	"eil51" : 426,
	"eil76" : 538,
	"eil101" : 629,
	"fl417" : 11861,
	"fl1400" : 20127,
	"fl1577" : 22249,
	"fl3795" : 28772,
	"fnl4461" : 182566,
	"fri26" : 937,
	"gil262" : 2378,
	"gr17" : 2085,
	"gr21" : 2707,
	"gr24" : 1272,
	"gr48" : 5046,
	"gr96" : 55209,
	"gr120" : 6942,
	"gr137" : 69853,
	"gr202" : 40160,
	"gr229" : 134602,
	"gr431" : 171414,
	"gr666" : 294358,
	"hk48" : 11461,
	"kroA100" : 21282,
	"kroB100" : 22141,
	"kroC100" : 20749,
	"kroD100" : 21294,
	"kroE100" : 22068,
	"kroA150" : 26524,
	"kroB150" : 26130,
	"kroA200" : 29368,
	"kroB200" : 29437,
	"lin105" : 14379,
	"lin318" : 42029,
	"linhp318" : 41345,
	"nrw1379" : 56638,
	"p654" : 34643,
	"pa561" : 2763,
	"pcb442" : 50778,
	"pcb1173" : 56892,
	"pcb3038" : 137694,
	"pla7397" : 23260728,
	"pla33810" : 66048945,
	"pla85900" : 142382641,
	"pr76" : 108159,
	"pr107" : 44303,
	"pr124" : 59030,
	"pr136" : 96772,
	"pr144" : 58537,
	"pr152" : 73682,
	"pr226" : 80369,
	"pr264" : 49135,
	"pr299" : 48191,
	"pr439" : 107217,
	"pr1002" : 259045,
	"pr2392" : 378032,
	"rat99" : 1211,
	"rat195" : 2323,
	"rat575" : 6773,
	"rat783" : 8806,
	"rd100" : 7910,
	"rd400" : 15281,
	"rl1304" : 252948,
	"rl1323" : 270199,
	"rl1889" : 316536,
	"rl5915" : 565530,
	"rl5934" : 556045,
	"rl11849" : 923288,
	"si175" : 21407,
	"si535" : 48450,
	"si1032" : 92650,
	"st70" : 675,
	"swiss42" : 1273,
	"ts225" : 126643,
	"tsp225" : 3916,
	"u159" : 42080,
	"u574" : 36905,
	"u724" : 41910,
	"u1060" : 224094,
	"u1432" : 152970,
	"u1817" : 57201,
	"u2152" : 64253,
	"u2319" : 234256,
	"ulysses16" : 6859,
	"ulysses22" : 7013,
	"usa13509" : 19982859,
	"vm1084" : 239297,
	"vm1748" : 336556,
}

In [4]:
## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
print(pd.DataFrame(initial_batch))

    alpha   beta    rho  ants  nnls  elitistants  localsearch  dlb
0   5.189  6.773  0.866    49    38          614            0    1
1   3.530  7.017  0.749    27    24          461            3    0
2   3.103  5.650  0.405    20    40          352            1    0
3   4.809  4.447  0.185    81    22          722            3    0
4   8.434  3.444  0.507     8    46          622            2    0
5   7.902  3.237  0.967    43    17          542            1    1
6   6.375  2.953  0.633    96    26          718            1    1
7   6.865  6.417  0.586    34    37          643            0    0
8   5.744  2.042  0.516    92    19          228            0    1
9   2.420  7.699  0.443    78    29          675            3    0
10  2.948  8.826  0.206     5    10          496            0    1
11  2.032  4.830  0.367    44    44          129            2    1
12  2.207  6.357  0.664    87    41          396            1    1
13  9.220  4.106  0.346    19    49           10            2    0
14  2.762  4.045  0.134    36    21           22            1    1
15  1.263  5.053  0.908    51    29          388            3    0
16  6.967  9.670  0.228    71    23          667            3    0
17  6.127  4.364  0.478    74    44          267            3    1
18  7.204  1.057  0.854    91    39          222            1    1
19  6.577  8.535  0.573    38    26          209            3    1
20  1.765  6.161  0.264    84    45          298            3    1
21  9.300  7.137  0.880    57    29          493            2    1
22  1.085  5.330  0.434    60     9          361            0    1
23  8.671  8.090  0.924    16    19          142            2    0
24  8.281  2.673  0.938    99    30          304            0    0
25  7.686  3.867  0.103    13    34          565            1    1
26  8.856  7.445  0.947    80    24           92            0    0
27  7.653  3.531  0.320    68     9          690            2    1
28  4.343  1.708  0.791    42    31          744            2    1
29  8.153  8.703  0.250    66    42          343            3    1
30  4.237  6.593  0.688    70    16          651            2    1
31  7.417  9.627  0.371    14     9          513            2    1
32  1.412  5.311  0.308    26    45           43            2    1
33  6.011  8.922  0.551    24    26          326            1    1
34  5.587  2.333  0.774    94    43          419            3    0
35  3.187  1.491  0.811    63    26          476            1    0
36  3.852  5.796  0.730    76    37           64            2    1
37  1.709  4.676  0.821     7     8          248            3    1
38  9.929  2.504  0.614    39    30          173            2    1
39  5.037  7.904  0.165    30    36          119            1    0
40  9.749  7.551  0.549    10    48          592            0    1
41  2.476  9.196  0.707    55    29          582            1    1
42  9.521  8.219  0.647    82    30          278            1    1
43  6.700  1.200  0.408    89    34          187            1    0
44  4.693  9.315  0.212    58    25           47            0    0
45  3.467  3.105  0.726    62    45          433            0    1
46  9.031  2.086  0.476    53    31           84            0    0
47  4.025  9.871  0.290    32    34          529            3    0
48  4.449  5.949  0.984    23    23          163            1    1
49  5.375  1.793  0.139    46     8          449            3    0

In [5]:
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
16,2.012,7.034,0.206,25.0,19.0,245.0,1.0,1.0,13,-0.000000
30,2.207,6.357,0.689,87.0,27.0,352.0,1.0,1.0,10,-0.000000
29,2.350,4.453,0.891,78.0,29.0,263.0,2.0,1.0,19,-0.000000
4,1.765,6.161,0.264,14.0,45.0,153.0,0.0,1.0,8,-0.000000
45,9.749,4.710,0.549,34.0,48.0,592.0,2.0,1.0,14,-0.000000
9,2.948,8.826,0.206,100.0,10.0,496.0,0.0,1.0,1,-0.000000
17,8.153,9.242,0.250,66.0,42.0,382.0,3.0,0.0,12,-0.000000
31,2.350,4.453,0.443,78.0,29.0,263.0,2.0,1.0,9,0.001714
40,2.459,7.714,0.496,66.0,21.0,503.0,2.0,1.0,8,0.007480
18,8.955,6.868,0.197,49.0,19.0,245.0,3.0,0.0,10,0.007946
11,2.948,6.680,0.206,58.0,19.0,245.0,0.0,1.0,8,0.017301
20,2.459,8.703,0.250,66.0,11.0,484.0,2.0,1.0,2,0.019566
7,2.459,8.703,0.250,66.0,11.0,338.0,2.0,1.0,14,0.021322
12,8.153,7.617,0.250,66.0,42.0,382.0,3.0,0.0,17,0.021814
24,2.106,3.801,0.516,87.0,21.0,276.0,1.0,1.0,7,0.052656
3,2.032,4.830,0.367,37.0,44.0,729.0,2.0,1.0,4,0.054911
6,9.749,4.710,0.549,34.0,48.0,592.0,1.0,1.0,11,0.064063
47,9.749,7.551,0.463,34.0,48.0,592.0,0.0,1.0,15,0.073813
39,6.700,1.200,0.408,89.0,18.0,187.0,1.0,0.0,1,0.079483
8,2.207,6.357,0.664,87.0,27.0,352.0,1.0,1.0,5,0.082149
13,2.459,4.374,0.411,66.0,42.0,547.0,0.0,1.0,13,0.102090
43,5.277,8.542,0.250,88.0,23.0,484.0,0.0,1.0,16,0.106402
19,2.459,8.542,0.250,66.0,11.0,484.0,2.0,1.0,3,0.116415
10,2.207,6.357,0.664,84.0,24.0,352.0,1.0,1.0,9,0.120181
34,3.133,9.447,0.627,26.0,11.0,92.0,0.0,1.0,8,0.123238
25,2.948,9.228,0.206,62.0,10.0,566.0,0.0,1.0,16,0.128026
33,1.765,6.161,0.639,64.0,7.0,150.0,1.0,1.0,11,0.149098
23,8.955,6.680,0.197,49.0,19.0,245.0,2.0,1.0,9,0.149769
32,2.350,4.453,0.895,78.0,29.0,263.0,2.0,1.0,10,0.150091
48,2.106,3.801,0.516,87.0,21.0,276.0,1.0,0.0,19,0.152886
1,2.207,6.357,0.664,57.0,27.0,246.0,1.0,1.0,7,0.161445
22,2.207,6.357,0.664,87.0,27.0,246.0,1.0,1.0,6,0.167427
37,1.765,6.161,0.889,64.0,29.0,495.0,3.0,1.0,10,0.189994
15,1.765,6.161,0.264,84.0,43.0,298.0,3.0,1.0,4,0.197965
49,1.765,6.161,0.264,75.0,6.0,94.0,3.0,1.0,9,0.218934
41,9.921,8.626,0.627,88.0,44.0,92.0,0.0,0.0,8,0.226569
36,1.765,6.161,0.889,84.0,25.0,495.0,3.0,1.0,12,0.235724
5,2.459,4.374,0.250,66.0,11.0,547.0,0.0,1.0,8,0.239391
38,6.700,1.200,0.542,52.0,48.0,408.0,1.0,0.0,9,0.281397
28,7.315,7.714,0.496,80.0,21.0,503.0,3.0,0.0,15,0.299788
14,2.459,4.374,0.411,66.0,42.0,547.0,2.0,1.0,16,0.308848
42,5.277,8.542,0.250,88.0,23.0,484.0,2.0,1.0,11,0.314229
26,8.955,6.680,0.197,49.0,26.0,245.0,2.0,1.0,13,0.493084
27,3.262,4.045,0.121,36.0,21.0,22.0,2.0,0.0,18,0.495869
0,9.749,7.551,0.549,34.0,48.0,592.0,0.0,1.0,1,0.500541
2,2.848,8.438,0.264,14.0,45.0,153.0,3.0,1.0,18,0.538299
35,5.664,7.849,0.819,13.0,27.0,246.0,1.0,1.0,15,0.561706
46,3.262,4.045,0.134,36.0,21.0,22.0,1.0,0.0,8,0.628236
21,4.048,4.045,0.134,14.0,21.0,173.0,2.0,1.0,7,0.681306
44,2.176,9.801,0.250,66.0,47.0,547.0,3.0,1.0,17,0.971462

In [4]:
## MAKE SEED
SEED = evotoon.make_seed(283)
separator = "--------------------------------------------------------"
## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
# 2830m 58.3s
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
19,1.862,4.887,0.146,17.0,46.0,680.0,0.0,1.0,17,-0.000000
43,1.767,8.431,0.425,73.0,48.0,179.0,1.0,1.0,10,-0.000000
37,3.327,6.725,0.188,61.0,20.0,423.0,0.0,0.0,19,-0.000000
31,4.035,5.968,0.114,45.0,17.0,139.0,1.0,0.0,0,-0.000000
15,1.767,4.512,0.425,73.0,20.0,490.0,1.0,1.0,16,-0.000000
6,1.570,1.808,0.118,59.0,36.0,546.0,0.0,0.0,11,-0.000000
44,1.570,1.808,0.961,99.0,21.0,168.0,2.0,1.0,19,-0.000000
4,1.862,5.373,0.146,17.0,44.0,383.0,0.0,1.0,18,-0.000000
21,1.063,1.808,0.884,59.0,14.0,168.0,3.0,1.0,9,-0.000000
5,1.570,1.808,0.701,59.0,36.0,168.0,0.0,1.0,16,-0.000000
48,1.526,6.221,0.961,55.0,41.0,272.0,2.0,1.0,19,0.005057
23,1.570,1.808,0.961,99.0,21.0,119.0,0.0,1.0,18,0.010631
46,1.526,8.641,0.338,69.0,17.0,624.0,2.0,1.0,14,0.015766
42,3.413,6.381,0.188,61.0,20.0,423.0,0.0,1.0,9,0.015898
32,6.182,7.057,0.961,55.0,17.0,65.0,2.0,1.0,18,0.018809
7,1.063,1.808,0.884,59.0,14.0,168.0,1.0,1.0,15,0.020441
27,1.184,7.405,0.945,50.0,30.0,517.0,0.0,0.0,16,0.023839
14,3.802,3.706,0.514,9.0,40.0,522.0,0.0,1.0,17,0.025313
36,1.731,7.324,0.945,73.0,30.0,517.0,0.0,1.0,16,0.027005
28,1.862,7.033,0.146,17.0,44.0,383.0,0.0,1.0,19,0.047202
30,1.862,4.887,0.146,17.0,44.0,680.0,0.0,1.0,14,0.053092
33,7.047,7.733,0.129,41.0,35.0,159.0,1.0,1.0,16,0.058697
35,2.570,5.526,0.987,43.0,35.0,13.0,0.0,1.0,16,0.064459
3,1.526,7.381,0.679,55.0,17.0,272.0,2.0,1.0,11,0.082663
22,1.862,5.373,0.344,90.0,47.0,680.0,0.0,1.0,6,0.085313
13,1.526,7.381,0.961,55.0,41.0,272.0,2.0,1.0,18,0.086978
40,1.570,1.808,0.319,59.0,36.0,168.0,0.0,1.0,13,0.091562
17,1.767,8.833,0.425,68.0,45.0,490.0,1.0,1.0,11,0.096245
45,4.488,5.381,0.366,89.0,8.0,74.0,0.0,0.0,8,0.097574
0,1.767,6.270,0.425,51.0,38.0,490.0,3.0,1.0,8,0.104835
2,1.767,7.733,0.425,68.0,45.0,490.0,1.0,1.0,8,0.112014
10,7.107,2.911,0.667,82.0,41.0,80.0,3.0,1.0,7,0.113925
47,1.767,7.733,0.425,94.0,20.0,490.0,3.0,1.0,9,0.123487
41,1.570,1.808,0.961,99.0,21.0,168.0,0.0,1.0,10,0.132434
9,1.526,7.381,0.850,55.0,17.0,304.0,2.0,1.0,19,0.133144
38,1.526,7.381,0.679,55.0,32.0,272.0,2.0,1.0,18,0.144429
34,4.035,5.968,0.114,31.0,17.0,139.0,1.0,0.0,16,0.155323
8,5.096,8.242,0.945,79.0,49.0,228.0,0.0,1.0,17,0.158294
25,1.767,8.033,0.425,10.0,45.0,490.0,1.0,1.0,14,0.179423
24,3.179,7.381,0.961,55.0,17.0,272.0,2.0,1.0,15,0.187077
26,1.767,7.733,0.425,73.0,23.0,490.0,1.0,1.0,4,0.193994
18,1.862,5.373,0.146,17.0,44.0,680.0,0.0,1.0,9,0.228804
11,3.327,6.381,0.188,61.0,20.0,423.0,0.0,1.0,16,0.238816
29,1.731,7.324,0.945,82.0,30.0,517.0,0.0,1.0,6,0.240931
49,3.802,9.657,0.514,85.0,24.0,522.0,0.0,1.0,17,0.266637
12,1.526,7.381,0.961,55.0,17.0,304.0,2.0,1.0,10,0.330077
20,1.862,5.373,0.344,96.0,47.0,680.0,0.0,1.0,12,0.330874
39,1.023,3.706,0.496,85.0,18.0,464.0,0.0,0.0,11,0.331463
1,7.047,7.733,0.425,68.0,45.0,159.0,1.0,1.0,9,0.548216
16,6.182,7.057,0.780,55.0,17.0,65.0,2.0,1.0,19,0.802454

In [4]:
## MAKE SEED
SEED = evotoon.make_seed(315)
separator = "--------------------------------------------------------"
## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
11,4.825,6.966,0.218,96.0,7.0,20.0,2.0,0.0,8,-0.000000
44,4.825,5.504,0.218,86.0,20.0,20.0,2.0,0.0,18,-0.000000
7,5.679,7.546,0.239,90.0,44.0,417.0,2.0,1.0,17,0.005143
25,1.382,8.951,0.767,42.0,19.0,376.0,3.0,1.0,17,0.011028
40,1.654,1.441,0.477,78.0,35.0,658.0,1.0,1.0,12,0.012826
17,4.070,7.322,0.616,68.0,25.0,208.0,1.0,1.0,13,0.025941
41,7.720,2.717,0.186,73.0,43.0,43.0,1.0,1.0,4,0.034347
5,2.413,1.483,0.406,81.0,10.0,81.0,0.0,1.0,14,0.037564
0,7.417,6.110,0.616,68.0,25.0,92.0,0.0,1.0,2,0.044766
1,7.051,1.441,0.431,50.0,18.0,239.0,1.0,1.0,5,0.048819
19,1.230,3.909,0.271,43.0,33.0,576.0,2.0,1.0,19,0.059990
10,4.096,1.441,0.431,50.0,18.0,239.0,1.0,1.0,13,0.061631
30,1.899,2.776,0.842,62.0,30.0,650.0,0.0,1.0,8,0.064696
45,8.435,2.827,0.216,62.0,30.0,719.0,2.0,1.0,17,0.064945
6,6.535,4.508,0.891,80.0,40.0,50.0,3.0,0.0,0,0.066140
3,1.382,3.465,0.767,42.0,19.0,376.0,3.0,1.0,14,0.067462
48,1.596,6.273,0.123,15.0,28.0,493.0,2.0,1.0,6,0.077706
20,1.230,3.909,0.809,55.0,24.0,576.0,1.0,1.0,8,0.086229
26,1.382,6.637,0.239,90.0,44.0,417.0,2.0,1.0,15,0.095289
37,1.230,3.909,0.271,55.0,24.0,576.0,1.0,1.0,16,0.098949
13,3.544,9.421,0.284,34.0,21.0,500.0,3.0,1.0,7,0.102421
12,1.596,6.273,0.123,15.0,28.0,493.0,0.0,1.0,5,0.103031
35,7.051,1.441,0.477,78.0,41.0,239.0,1.0,1.0,4,0.131779
24,1.382,9.742,0.767,53.0,31.0,376.0,2.0,1.0,10,0.132010
21,1.230,3.794,0.641,26.0,24.0,428.0,3.0,1.0,11,0.139499
42,6.161,4.508,0.891,92.0,40.0,50.0,3.0,0.0,2,0.144426
43,2.708,2.970,0.216,62.0,22.0,719.0,2.0,1.0,18,0.160005
8,4.070,8.897,0.616,68.0,25.0,208.0,1.0,1.0,18,0.167699
27,6.082,4.215,0.117,14.0,21.0,500.0,0.0,0.0,19,0.172649
33,3.544,9.538,0.286,87.0,21.0,179.0,3.0,1.0,14,0.188636
23,5.234,4.754,0.406,31.0,25.0,81.0,3.0,0.0,16,0.193148
38,4.754,8.970,0.714,64.0,21.0,14.0,3.0,0.0,3,0.201866
2,1.420,4.077,0.837,99.0,20.0,378.0,1.0,0.0,4,0.219254
31,4.880,9.440,0.822,97.0,15.0,448.0,1.0,1.0,11,0.221893
14,1.382,6.637,0.667,90.0,44.0,591.0,2.0,1.0,7,0.246323
29,7.725,4.206,0.667,90.0,44.0,591.0,0.0,1.0,19,0.258037
28,8.444,3.909,0.809,48.0,42.0,576.0,2.0,0.0,10,0.275776
4,1.596,6.273,0.123,28.0,28.0,493.0,0.0,1.0,13,0.285132
9,4.880,9.440,0.822,84.0,17.0,448.0,1.0,1.0,5,0.398927
34,8.435,2.827,0.216,62.0,32.0,719.0,2.0,1.0,10,0.410520
36,7.725,4.206,0.667,90.0,44.0,591.0,2.0,1.0,18,0.419647
47,4.754,8.970,0.470,64.0,21.0,14.0,3.0,0.0,19,0.434273
46,1.382,7.546,0.239,90.0,44.0,417.0,2.0,1.0,16,0.469949
22,1.382,9.742,0.460,53.0,31.0,376.0,2.0,1.0,12,0.500887
18,2.436,9.839,0.449,50.0,49.0,386.0,0.0,0.0,14,0.505178
49,1.596,6.273,0.123,15.0,13.0,493.0,0.0,1.0,19,0.505654
32,7.051,9.067,0.431,50.0,18.0,239.0,1.0,1.0,6,0.634853
16,3.544,9.538,0.164,87.0,21.0,179.0,3.0,1.0,18,0.659039
39,1.654,1.441,0.477,39.0,35.0,658.0,1.0,1.0,14,0.665842
15,6.161,4.508,0.891,15.0,40.0,225.0,3.0,0.0,14,0.691128

In [5]:
## MAKE SEED
SEED = evotoon.make_seed(39)
separator = "--------------------------------------------------------"
## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
1,1.098,7.289,0.294,94.0,17.0,368.0,3.0,0.0,14,-0.000000
38,1.097,4.520,0.909,66.0,47.0,383.0,3.0,0.0,17,-0.000000
41,1.098,6.696,0.288,16.0,24.0,165.0,1.0,1.0,19,0.022712
28,2.344,4.479,0.616,36.0,30.0,615.0,0.0,1.0,4,0.025158
36,1.098,7.569,0.305,77.0,20.0,165.0,1.0,0.0,18,0.029503
47,2.344,4.479,0.616,56.0,22.0,72.0,3.0,0.0,8,0.044239
30,1.098,2.966,0.288,16.0,24.0,179.0,2.0,0.0,14,0.054354
17,1.097,4.520,0.378,66.0,39.0,383.0,3.0,0.0,5,0.054854
22,3.268,4.479,0.803,72.0,25.0,260.0,0.0,1.0,16,0.062386
35,1.098,2.966,0.305,77.0,20.0,165.0,1.0,0.0,4,0.076567
25,1.507,9.654,0.369,92.0,10.0,578.0,2.0,1.0,6,0.090368
49,6.610,4.479,0.886,36.0,30.0,589.0,0.0,1.0,19,0.096960
5,1.098,6.696,0.288,16.0,24.0,165.0,2.0,0.0,8,0.109306
26,2.427,4.753,0.419,81.0,44.0,501.0,3.0,1.0,10,0.127416
7,2.427,4.753,0.419,81.0,44.0,455.0,3.0,1.0,8,0.129796
4,2.427,8.301,0.419,81.0,44.0,501.0,3.0,1.0,14,0.132442
34,2.080,7.437,0.674,92.0,40.0,459.0,3.0,1.0,13,0.135750
44,1.098,2.966,0.288,45.0,43.0,32.0,1.0,0.0,6,0.144339
12,1.098,7.289,0.993,16.0,17.0,165.0,1.0,0.0,13,0.145079
14,9.131,2.966,0.288,16.0,46.0,165.0,1.0,1.0,18,0.195457
32,7.218,9.284,0.419,38.0,10.0,127.0,3.0,1.0,19,0.200214
16,1.098,1.027,0.288,16.0,38.0,165.0,1.0,1.0,19,0.217535
33,1.098,5.846,0.288,16.0,24.0,179.0,2.0,0.0,19,0.218338
20,1.323,5.080,0.745,45.0,28.0,398.0,0.0,0.0,3,0.234535
27,2.344,4.479,0.616,44.0,25.0,13.0,0.0,1.0,7,0.247836
48,1.098,5.261,0.190,45.0,43.0,291.0,1.0,0.0,12,0.252751
46,3.278,9.628,0.745,45.0,28.0,359.0,1.0,0.0,19,0.269044
43,1.323,2.900,0.125,45.0,28.0,182.0,2.0,1.0,18,0.269559
9,1.097,4.520,0.378,66.0,39.0,383.0,0.0,0.0,18,0.302913
24,1.507,2.453,0.369,92.0,10.0,399.0,2.0,1.0,19,0.316717
0,1.098,8.003,0.288,56.0,24.0,165.0,1.0,1.0,10,0.330874
23,1.323,3.341,0.208,50.0,5.0,319.0,0.0,0.0,8,0.369273
29,2.344,4.479,0.616,56.0,25.0,13.0,0.0,1.0,7,0.427757
6,1.323,6.181,0.745,45.0,28.0,182.0,2.0,0.0,8,0.437720
31,8.278,9.277,0.770,97.0,33.0,142.0,0.0,1.0,3,0.446780
45,1.098,3.104,0.536,16.0,24.0,165.0,3.0,0.0,19,0.476732
39,1.098,2.966,0.288,64.0,24.0,165.0,1.0,0.0,7,0.483821
15,5.021,2.966,0.398,77.0,20.0,165.0,2.0,0.0,14,0.514854
42,2.080,5.194,0.591,92.0,40.0,578.0,0.0,1.0,19,0.531916
18,1.098,8.902,0.536,16.0,24.0,165.0,3.0,0.0,11,0.562314
13,3.668,9.747,0.143,74.0,16.0,150.0,0.0,0.0,6,0.567020
8,1.507,2.453,0.369,92.0,10.0,578.0,2.0,1.0,9,0.596180
3,1.023,8.577,0.288,65.0,24.0,165.0,1.0,0.0,8,0.648113
21,3.000,4.687,0.271,74.0,16.0,268.0,0.0,0.0,11,0.650580
19,6.139,5.307,0.909,49.0,47.0,383.0,3.0,0.0,19,0.655449
2,1.098,6.696,0.288,16.0,33.0,165.0,2.0,0.0,18,0.667638
10,3.268,7.197,0.616,72.0,22.0,260.0,0.0,1.0,19,0.686813
40,1.098,5.261,0.288,45.0,43.0,291.0,1.0,0.0,7,0.717286
11,1.081,5.095,0.501,13.0,10.0,83.0,3.0,1.0,2,0.756532
37,1.323,8.403,0.745,45.0,28.0,182.0,2.0,0.0,19,0.929272

In [6]:
## MAKE SEED
SEED = evotoon.make_seed(346)
separator = "--------------------------------------------------------"
## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
21,1.641,9.577,0.417,80.0,50.0,527.0,2.0,1.0,18,-0.000000
13,1.258,9.101,0.436,24.0,35.0,543.0,1.0,0.0,18,-0.000000
3,2.500,7.138,0.312,92.0,15.0,616.0,3.0,1.0,10,-0.000000
37,1.882,4.834,0.485,72.0,46.0,375.0,3.0,0.0,19,-0.000000
0,2.019,9.577,0.481,68.0,31.0,228.0,1.0,1.0,14,0.002890
23,1.576,6.032,0.230,73.0,28.0,558.0,3.0,0.0,19,0.005057
48,2.905,7.229,0.533,39.0,33.0,97.0,3.0,1.0,19,0.027891
42,2.500,7.138,0.287,88.0,46.0,257.0,3.0,1.0,17,0.036842
2,3.339,1.134,0.162,63.0,14.0,138.0,2.0,1.0,5,0.050934
15,3.980,7.229,0.223,39.0,33.0,626.0,2.0,1.0,8,0.053727
22,8.576,9.576,0.272,24.0,28.0,18.0,2.0,1.0,14,0.059212
33,1.576,9.705,0.230,9.0,28.0,53.0,1.0,1.0,8,0.072062
38,5.613,5.854,0.230,78.0,28.0,50.0,1.0,1.0,19,0.077164
4,2.019,1.220,0.417,80.0,14.0,527.0,2.0,1.0,9,0.079657
40,1.864,9.611,0.825,91.0,9.0,107.0,0.0,0.0,3,0.084487
20,1.106,1.978,0.532,53.0,42.0,359.0,2.0,0.0,15,0.091593
14,1.882,2.901,0.368,95.0,40.0,637.0,3.0,1.0,1,0.116810
47,2.373,1.016,0.189,79.0,19.0,169.0,0.0,1.0,18,0.117998
8,4.449,6.510,0.735,59.0,10.0,73.0,2.0,1.0,8,0.123345
9,3.785,5.558,0.272,24.0,28.0,18.0,2.0,1.0,17,0.149695
10,2.373,1.016,0.189,63.0,19.0,138.0,2.0,1.0,11,0.149723
19,3.980,7.229,0.336,39.0,33.0,408.0,2.0,1.0,14,0.155590
34,4.206,6.831,0.542,39.0,24.0,138.0,2.0,1.0,18,0.169776
35,2.509,9.577,0.292,56.0,31.0,197.0,1.0,1.0,15,0.182270
17,2.500,6.490,0.312,88.0,15.0,616.0,3.0,1.0,0,0.223896
49,7.618,7.229,0.113,80.0,28.0,220.0,0.0,0.0,19,0.247837
41,1.882,4.834,0.485,72.0,47.0,375.0,3.0,0.0,16,0.272754
27,2.500,7.138,0.312,92.0,21.0,616.0,3.0,1.0,16,0.281613
43,2.019,6.641,0.417,80.0,17.0,355.0,1.0,0.0,11,0.283839
18,1.258,9.101,0.272,24.0,35.0,543.0,1.0,0.0,13,0.338390
5,2.905,7.229,0.113,80.0,28.0,220.0,3.0,1.0,14,0.338727
44,2.373,1.016,0.189,63.0,33.0,138.0,2.0,1.0,4,0.344714
32,2.019,9.577,0.417,80.0,14.0,527.0,2.0,0.0,12,0.351735
29,2.523,6.510,0.735,59.0,10.0,73.0,2.0,1.0,19,0.369631
30,4.454,6.831,0.189,63.0,33.0,138.0,2.0,1.0,19,0.372104
7,1.576,5.470,0.230,73.0,28.0,558.0,0.0,1.0,18,0.427650
1,1.393,9.395,0.596,12.0,47.0,510.0,3.0,0.0,7,0.448296
26,6.434,8.751,0.454,91.0,18.0,73.0,0.0,1.0,13,0.456230
36,2.500,7.138,0.312,88.0,46.0,616.0,3.0,1.0,13,0.457860
31,2.019,1.220,0.417,80.0,14.0,403.0,3.0,1.0,17,0.477199
24,1.882,2.901,0.944,95.0,41.0,637.0,3.0,1.0,13,0.511152
39,1.882,2.901,0.944,95.0,40.0,637.0,3.0,1.0,12,0.561222
45,1.393,7.564,0.596,12.0,41.0,435.0,3.0,0.0,19,0.584028
11,4.454,6.831,0.189,63.0,24.0,138.0,2.0,1.0,9,0.668023
25,2.905,7.229,0.953,39.0,33.0,97.0,3.0,1.0,8,0.668418
12,8.402,6.721,0.702,74.0,13.0,544.0,0.0,1.0,1,0.784012
6,8.576,9.101,0.272,24.0,28.0,18.0,2.0,1.0,5,0.797271
16,2.019,9.577,0.481,38.0,31.0,286.0,1.0,1.0,4,0.877666
28,5.769,3.296,0.483,77.0,8.0,156.0,0.0,1.0,15,0.935364
46,2.500,7.138,0.287,88.0,46.0,257.0,3.0,0.0,19,0.960337