In [1]:
## IMPORTS 
import evotoon
from data_classes import CatParam, IntParam, FloatParam


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#import seaborn as sns#

import random
import warnings
warnings.filterwarnings("ignore")

In [2]:
## MAKE SEED
SEED = evotoon.make_seed(765)
separator = "--------------------------------------------------------"

In [3]:
optimal_solutions = {
	"a280" : 2579,
	"ali535" : 202339,
	"att48" : 10628,
	"att532" : 27686,
	"bayg29" : 1610,
	"bays29" : 2020,
	"berlin52" : 7542,
	"bier127" : 118282,
	"brazil58" : 25395,
	"brd14051" : 469385,
	"brg180" : 1950,
	"burma14" : 3323,
	"ch130" : 6110,
	"ch150" : 6528,
	"d198" : 15780,
	"d493" : 35002,
	"d657" : 48912,
	"d1291" : 50801,
	"d1655" : 62128,
	"d2103" : 80450,
	"d15112" : 1573084,
	"d18512" : 645238,
	"dantzig42" : 699,
	"dsj1000" : 18659688, 
	"dsj1000" : 18660188,
	"eil51" : 426,
	"eil76" : 538,
	"eil101" : 629,
	"fl417" : 11861,
	"fl1400" : 20127,
	"fl1577" : 22249,
	"fl3795" : 28772,
	"fnl4461" : 182566,
	"fri26" : 937,
	"gil262" : 2378,
	"gr17" : 2085,
	"gr21" : 2707,
	"gr24" : 1272,
	"gr48" : 5046,
	"gr96" : 55209,
	"gr120" : 6942,
	"gr137" : 69853,
	"gr202" : 40160,
	"gr229" : 134602,
	"gr431" : 171414,
	"gr666" : 294358,
	"hk48" : 11461,
	"kroA100" : 21282,
	"kroB100" : 22141,
	"kroC100" : 20749,
	"kroD100" : 21294,
	"kroE100" : 22068,
	"kroA150" : 26524,
	"kroB150" : 26130,
	"kroA200" : 29368,
	"kroB200" : 29437,
	"lin105" : 14379,
	"lin318" : 42029,
	"linhp318" : 41345,
	"nrw1379" : 56638,
	"p654" : 34643,
	"pa561" : 2763,
	"pcb442" : 50778,
	"pcb1173" : 56892,
	"pcb3038" : 137694,
	"pla7397" : 23260728,
	"pla33810" : 66048945,
	"pla85900" : 142382641,
	"pr76" : 108159,
	"pr107" : 44303,
	"pr124" : 59030,
	"pr136" : 96772,
	"pr144" : 58537,
	"pr152" : 73682,
	"pr226" : 80369,
	"pr264" : 49135,
	"pr299" : 48191,
	"pr439" : 107217,
	"pr1002" : 259045,
	"pr2392" : 378032,
	"rat99" : 1211,
	"rat195" : 2323,
	"rat575" : 6773,
	"rat783" : 8806,
	"rd100" : 7910,
	"rd400" : 15281,
	"rl1304" : 252948,
	"rl1323" : 270199,
	"rl1889" : 316536,
	"rl5915" : 565530,
	"rl5934" : 556045,
	"rl11849" : 923288,
	"si175" : 21407,
	"si535" : 48450,
	"si1032" : 92650,
	"st70" : 675,
	"swiss42" : 1273,
	"ts225" : 126643,
	"tsp225" : 3916,
	"u159" : 42080,
	"u574" : 36905,
	"u724" : 41910,
	"u1060" : 224094,
	"u1432" : 152970,
	"u1817" : 57201,
	"u2152" : 64253,
	"u2319" : 234256,
	"ulysses16" : 6859,
	"ulysses22" : 7013,
	"usa13509" : 19982859,
	"vm1084" : 239297,
	"vm1748" : 336556,
}

In [5]:
## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
model_kwargs = {
	"layers": 4,
	"neurons": 4 * [6]
}
print(pd.DataFrame(initial_batch))

    alpha   beta    rho  ants  nnls  elitistants  localsearch  dlb
0   2.535  7.681  0.192    60    47          536            1    0
1   3.848  7.545  0.337    15    28          639            3    0
2   2.245  3.954  0.113    84    46          443            0    0
3   8.278  3.672  0.298    10    23           83            3    0
4   5.926  3.051  0.875    87    49          461            1    1
5   2.008  2.877  0.958    38     9          128            0    1
6   3.678  4.487  0.403    74    10          542            0    1
7   5.828  4.987  0.814     7    12           27            2    0
8   7.592  1.637  0.457    65    40          151            3    0
9   7.467  6.156  0.750    72    43          513            1    0
10  2.832  5.386  0.989    12    16          178            3    0
11  8.997  7.238  0.625    51    25          689            3    0
12  1.861  3.447  0.682    83     8          614            1    1
13  8.111  6.584  0.781    96    21          474            1    1
14  9.753  2.165  0.615    35     9          712            0    0
15  5.497  3.321  0.823    17    10          244            1    0
16  9.481  4.819  0.554    89    12            6            2    0
17  7.964  9.472  0.643     9    23          389            2    1
18  6.627  2.427  0.146    76    24          279            2    0
19  5.214  5.525  0.900    45    43          185            1    1
20  4.787  9.733  0.215    99    22          306            3    1
21  6.122  6.792  0.124    47    25          555            0    1
22  6.554  9.955  0.354    43    43          671            0    1
23  2.758  7.979  0.727    23    43          204            2    1
24  2.329  8.274  0.854    77    13          221            0    0
25  9.408  8.442  0.439    56    48          577            3    0
26  1.284  1.490  0.596    62    24          319            2    1
27  8.667  1.728  0.731    40    29          615            1    1
28  7.017  4.103  0.944    54    36          741            2    1
29  1.063  9.152  0.249    53     8          654            2    0
30  8.493  1.036  0.542    70    27           68            3    1
31  1.470  8.940  0.669    63    22          495            2    0
32  3.414  8.142  0.158    93    25          371            0    1
33  4.049  5.999  0.497    42    49          691            3    1
34  4.960  6.463  0.229    20    45          296            2    0
35  1.682  1.297  0.785    25    47          402            0    1
36  6.820  4.271  0.704    29    32          585            1    1
37  9.825  6.247  0.568    34     8           49            0    0
38  3.319  8.590  0.176    27    27          269            2    1
39  4.097  8.916  0.406    94    44          115            3    0
40  7.159  2.593  0.872    48    48          335            3    0
41  7.831  5.218  0.283    24    19          412            1    0
42  4.654  2.007  0.495    59    13          493            2    0
43  6.366  7.395  0.262    67    17          233            1    1
44  9.172  9.318  0.475     5    38          727            3    0
45  4.315  5.750  0.970    81    32           32            2    0
46  8.755  3.779  0.921    90    43          100            1    1
47  4.438  7.022  0.521    31    18          141            2    0
48  3.121  2.747  0.321    18    27          421            1    1
49  5.654  4.771  0.375    80    23          355            3    1

In [6]:
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, model_kwargs=model_kwargs, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
14,3.552,8.274,0.320,53.0,22.0,221.0,3.0,0.0,15,-0.000000
44,4.403,8.261,0.195,63.0,42.0,81.0,3.0,1.0,16,0.001714
11,2.593,2.446,0.116,97.0,39.0,88.0,3.0,1.0,12,0.003937
46,1.531,5.275,0.702,61.0,19.0,88.0,3.0,0.0,19,0.018905
22,1.628,8.274,0.203,96.0,13.0,580.0,3.0,0.0,15,0.043048
35,1.384,5.026,0.375,64.0,17.0,512.0,3.0,0.0,7,0.081762
16,1.455,1.036,0.133,5.0,27.0,493.0,3.0,1.0,14,0.098306
33,3.552,8.274,0.320,53.0,25.0,221.0,3.0,0.0,19,0.121044
45,3.674,5.161,0.304,97.0,39.0,88.0,3.0,1.0,19,0.132902
0,3.552,8.274,0.320,89.0,39.0,221.0,3.0,1.0,13,0.137611
49,6.756,8.274,0.320,83.0,22.0,221.0,3.0,0.0,18,0.147424
41,3.552,8.274,0.320,55.0,22.0,221.0,3.0,1.0,11,0.160401
43,5.399,5.985,0.322,34.0,25.0,204.0,3.0,1.0,16,0.161316
31,3.552,8.274,0.320,83.0,22.0,221.0,3.0,1.0,17,0.175770
25,4.121,5.161,0.305,97.0,39.0,159.0,3.0,1.0,19,0.188494
24,4.121,5.161,0.604,97.0,39.0,88.0,3.0,1.0,17,0.191242
23,3.552,8.562,0.203,80.0,13.0,221.0,3.0,0.0,13,0.197414
19,4.935,6.356,0.236,22.0,27.0,65.0,3.0,0.0,17,0.199299
36,5.365,8.619,0.864,66.0,19.0,62.0,3.0,1.0,13,0.204885
20,5.365,8.619,0.864,66.0,25.0,62.0,3.0,1.0,14,0.208724
1,4.508,5.684,0.375,76.0,17.0,77.0,3.0,1.0,15,0.219326
17,1.312,5.985,0.607,34.0,30.0,204.0,3.0,0.0,7,0.227056
15,3.674,5.161,0.604,97.0,39.0,88.0,3.0,1.0,13,0.227299
38,2.758,9.302,0.604,97.0,39.0,88.0,3.0,1.0,17,0.230836
4,3.674,4.351,0.604,97.0,39.0,88.0,3.0,1.0,18,0.245060
21,4.055,8.261,0.195,49.0,26.0,247.0,3.0,1.0,19,0.262176
9,2.758,5.161,0.604,100.0,39.0,88.0,3.0,1.0,16,0.266202
18,7.939,9.733,0.215,87.0,47.0,747.0,3.0,1.0,8,0.267946
2,5.365,8.758,0.102,58.0,19.0,104.0,3.0,0.0,17,0.277258
5,1.096,8.047,0.800,64.0,36.0,463.0,3.0,1.0,12,0.290492
6,5.365,5.163,0.681,67.0,19.0,288.0,3.0,1.0,9,0.312483
7,4.004,8.261,0.195,49.0,26.0,314.0,3.0,1.0,18,0.313436
10,1.096,7.107,0.304,71.0,36.0,680.0,3.0,1.0,8,0.347577
27,2.758,7.979,0.727,34.0,43.0,243.0,3.0,0.0,15,0.354267
13,7.171,5.985,0.322,34.0,43.0,204.0,3.0,1.0,11,0.354744
12,6.466,5.275,0.165,97.0,20.0,88.0,3.0,1.0,18,0.377769
28,3.552,8.274,0.203,96.0,13.0,221.0,3.0,0.0,7,0.442559
48,3.552,8.562,0.203,40.0,13.0,340.0,3.0,0.0,16,0.447281
3,3.552,8.562,0.203,80.0,13.0,221.0,3.0,1.0,19,0.457279
32,1.628,8.723,0.190,42.0,13.0,638.0,3.0,0.0,19,0.484665
26,4.004,8.261,0.195,49.0,26.0,247.0,3.0,1.0,15,0.486686
8,3.552,8.562,0.116,80.0,13.0,221.0,3.0,0.0,17,0.507805
42,5.365,8.619,0.362,66.0,19.0,62.0,3.0,1.0,19,0.525481
37,2.593,2.446,0.116,62.0,39.0,88.0,3.0,1.0,17,0.559290
40,2.758,5.161,0.604,97.0,39.0,88.0,3.0,1.0,6,0.618048
30,6.071,8.619,0.406,34.0,19.0,62.0,3.0,1.0,13,0.661448
34,5.905,3.672,0.298,10.0,23.0,173.0,3.0,0.0,11,0.686435
29,4.049,5.999,0.159,80.0,32.0,698.0,3.0,1.0,14,0.708597
39,2.758,6.441,0.604,80.0,37.0,511.0,3.0,0.0,19,0.768622
47,2.758,5.161,0.604,97.0,39.0,511.0,3.0,1.0,18,0.937312

In [7]:
SEED = evotoon.make_seed(283)

## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
model_kwargs = {
	"layers": 4,
	"neurons": 4 * [6]
}

evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, model_kwargs=model_kwargs, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
24,5.587,6.546,0.118,90.0,45.0,714.0,3.0,0.0,1,-0.000000
23,9.055,8.282,0.434,21.0,44.0,662.0,3.0,1.0,13,-0.000000
13,3.079,3.561,0.596,97.0,44.0,662.0,3.0,1.0,13,0.008208
28,8.814,2.607,0.711,71.0,44.0,41.0,3.0,1.0,17,0.013696
38,8.002,9.334,0.850,29.0,15.0,301.0,3.0,1.0,13,0.029630
29,9.107,4.645,0.182,43.0,43.0,355.0,3.0,1.0,0,0.051877
37,1.023,4.200,0.759,62.0,36.0,729.0,3.0,0.0,1,0.064459
45,1.023,4.200,0.786,62.0,36.0,729.0,3.0,0.0,15,0.065015
32,2.110,8.843,0.787,67.0,28.0,594.0,3.0,0.0,11,0.068096
49,1.489,9.334,0.850,29.0,20.0,301.0,3.0,1.0,8,0.088512
8,1.862,6.167,0.734,87.0,37.0,680.0,3.0,1.0,14,0.104920
5,1.862,6.167,0.263,87.0,44.0,206.0,2.0,1.0,6,0.111466
3,1.023,8.145,0.759,51.0,31.0,729.0,3.0,1.0,9,0.115142
0,7.709,5.803,0.490,71.0,34.0,57.0,3.0,0.0,10,0.118293
12,3.079,9.347,0.711,75.0,44.0,662.0,3.0,1.0,19,0.124211
35,1.023,6.044,0.482,62.0,22.0,729.0,3.0,0.0,10,0.126036
33,3.804,2.069,0.434,21.0,44.0,662.0,3.0,1.0,8,0.128569
48,3.079,9.347,0.711,71.0,44.0,567.0,3.0,1.0,10,0.129189
10,1.862,6.167,0.734,75.0,45.0,241.0,2.0,1.0,11,0.130030
47,1.023,6.044,0.759,62.0,22.0,729.0,3.0,1.0,8,0.133829
34,2.110,8.176,0.787,24.0,28.0,332.0,3.0,0.0,5,0.158983
31,9.107,9.843,0.182,43.0,43.0,355.0,3.0,1.0,7,0.176528
43,2.240,8.025,0.182,43.0,43.0,624.0,3.0,0.0,12,0.210983
25,2.240,4.645,0.454,43.0,36.0,119.0,3.0,1.0,14,0.219166
46,1.862,6.167,0.526,87.0,37.0,680.0,3.0,1.0,19,0.219637
16,5.587,5.530,0.771,90.0,45.0,153.0,3.0,0.0,7,0.225875
15,1.023,4.200,0.206,37.0,36.0,729.0,3.0,0.0,8,0.267798
1,3.079,9.347,0.711,71.0,41.0,567.0,3.0,1.0,18,0.300021
11,1.397,6.044,0.759,62.0,22.0,729.0,3.0,0.0,12,0.326879
20,3.021,3.708,0.434,21.0,44.0,662.0,3.0,1.0,7,0.337770
4,3.079,9.347,0.711,71.0,44.0,662.0,3.0,1.0,7,0.385572
39,3.227,5.530,0.771,90.0,45.0,153.0,3.0,0.0,16,0.406681
44,9.055,8.282,0.273,10.0,44.0,662.0,3.0,1.0,15,0.431210
40,3.021,8.282,0.434,21.0,18.0,662.0,3.0,1.0,12,0.436461
17,1.862,6.167,0.734,87.0,45.0,680.0,2.0,1.0,3,0.447871
30,7.215,8.638,0.346,52.0,33.0,477.0,2.0,1.0,5,0.495117
42,1.256,6.515,0.961,71.0,36.0,729.0,3.0,1.0,18,0.498898
27,3.079,3.561,0.711,97.0,44.0,662.0,3.0,1.0,1,0.568527
22,9.814,4.645,0.182,43.0,43.0,624.0,3.0,1.0,10,0.592047
2,1.023,4.200,0.206,31.0,14.0,729.0,3.0,1.0,18,0.613833
21,1.945,3.561,0.206,21.0,44.0,662.0,3.0,1.0,6,0.628231
7,1.023,4.200,0.206,43.0,9.0,729.0,3.0,0.0,6,0.679773
14,8.487,8.799,0.287,15.0,40.0,332.0,3.0,1.0,1,0.722631
6,1.862,7.914,0.465,20.0,45.0,164.0,3.0,1.0,10,0.743100
18,1.023,4.200,0.206,92.0,9.0,729.0,3.0,1.0,9,0.746052
19,1.862,6.167,0.734,87.0,24.0,680.0,2.0,1.0,16,0.766020
36,1.023,4.182,0.759,62.0,36.0,715.0,3.0,0.0,19,0.770371
41,4.768,5.138,0.202,22.0,24.0,503.0,3.0,0.0,5,0.776090
9,7.709,5.803,0.850,71.0,34.0,159.0,3.0,0.0,19,0.789880
26,5.587,9.074,0.118,90.0,45.0,714.0,3.0,0.0,2,0.873108

In [8]:
SEED = evotoon.make_seed(315)

## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
model_kwargs = {
	"layers": 4,
	"neurons": 4 * [6]
}

evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, model_kwargs=model_kwargs, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
4,1.976,5.072,0.335,43.0,20.0,172.0,3.0,0.0,12,0.001267
18,4.832,1.152,0.639,47.0,27.0,70.0,3.0,1.0,5,0.019881
20,5.305,8.895,0.817,84.0,16.0,287.0,3.0,1.0,9,0.040469
30,1.899,2.776,0.362,62.0,47.0,650.0,3.0,0.0,0,0.041288
14,3.322,4.040,0.399,94.0,20.0,235.0,3.0,1.0,16,0.067468
44,3.465,9.421,0.286,82.0,21.0,649.0,3.0,1.0,10,0.073637
37,6.682,6.554,0.639,100.0,26.0,78.0,3.0,1.0,11,0.075606
8,3.540,4.508,0.871,80.0,14.0,50.0,3.0,1.0,17,0.098799
7,5.678,1.582,0.941,94.0,16.0,129.0,3.0,1.0,13,0.100363
25,2.235,4.335,0.248,88.0,21.0,592.0,3.0,1.0,19,0.106995
45,2.296,4.409,0.891,85.0,34.0,459.0,3.0,1.0,19,0.107270
16,3.338,8.192,0.928,92.0,20.0,266.0,3.0,1.0,6,0.111789
9,3.540,4.508,0.750,80.0,16.0,50.0,3.0,0.0,9,0.114613
10,5.432,1.744,0.186,73.0,43.0,43.0,3.0,1.0,6,0.116153
42,3.465,9.421,0.286,88.0,21.0,649.0,3.0,1.0,9,0.171356
23,1.976,5.018,0.790,43.0,19.0,377.0,3.0,1.0,13,0.176908
49,2.965,3.524,0.513,43.0,19.0,330.0,3.0,0.0,12,0.177738
15,2.296,4.409,0.891,85.0,34.0,394.0,3.0,1.0,13,0.184062
36,3.917,2.787,0.530,85.0,34.0,50.0,3.0,1.0,17,0.201604
21,8.134,9.112,0.286,43.0,21.0,179.0,3.0,1.0,15,0.205644
5,3.540,4.508,0.486,80.0,16.0,50.0,3.0,0.0,8,0.220147
43,3.917,2.787,0.530,100.0,34.0,50.0,3.0,1.0,19,0.225114
48,1.976,3.524,0.513,31.0,20.0,266.0,3.0,0.0,12,0.253215
11,3.360,5.317,0.399,57.0,22.0,119.0,3.0,0.0,9,0.272304
17,6.682,6.554,0.639,100.0,26.0,70.0,3.0,1.0,5,0.292046
13,1.899,2.776,0.362,93.0,18.0,503.0,3.0,0.0,14,0.299740
2,6.818,9.421,0.286,88.0,21.0,555.0,3.0,1.0,15,0.303057
29,4.148,9.770,0.399,92.0,42.0,667.0,3.0,1.0,12,0.303965
40,1.831,3.628,0.399,21.0,42.0,709.0,3.0,1.0,6,0.307901
46,2.235,4.335,0.248,88.0,21.0,215.0,3.0,1.0,17,0.338254
19,6.682,8.485,0.639,51.0,45.0,70.0,3.0,1.0,7,0.353075
0,3.338,8.192,0.928,95.0,20.0,266.0,3.0,1.0,9,0.354408
47,5.432,1.744,0.515,73.0,9.0,43.0,3.0,1.0,14,0.361114
33,8.934,4.508,0.367,79.0,16.0,50.0,3.0,0.0,16,0.366170
26,3.322,4.040,0.399,69.0,20.0,235.0,3.0,1.0,19,0.371835
32,3.465,9.421,0.240,88.0,21.0,649.0,3.0,1.0,18,0.403663
34,1.976,3.524,0.513,43.0,19.0,97.0,3.0,0.0,17,0.411085
39,4.148,9.770,0.399,94.0,42.0,667.0,3.0,1.0,4,0.416184
41,5.432,1.744,0.515,79.0,43.0,43.0,3.0,1.0,16,0.426482
12,1.752,1.694,0.639,47.0,50.0,70.0,3.0,1.0,17,0.426493
31,6.682,6.554,0.639,67.0,42.0,70.0,3.0,1.0,17,0.534172
22,1.976,9.284,0.790,31.0,19.0,377.0,3.0,1.0,16,0.552492
6,2.296,2.787,0.530,85.0,34.0,50.0,3.0,1.0,10,0.594238
3,1.976,3.524,0.513,43.0,20.0,266.0,3.0,0.0,3,0.601151
24,3.322,4.040,0.399,89.0,20.0,235.0,3.0,1.0,18,0.614758
1,4.832,1.152,0.639,75.0,27.0,70.0,3.0,1.0,17,0.660539
27,4.832,1.152,0.639,47.0,50.0,70.0,3.0,1.0,7,0.723461
35,3.465,9.694,0.395,88.0,21.0,381.0,3.0,1.0,19,0.771827
28,4.148,7.686,0.399,92.0,42.0,667.0,3.0,1.0,16,0.811200
38,3.338,8.192,0.217,92.0,23.0,266.0,3.0,1.0,19,0.863739

In [9]:
SEED = evotoon.make_seed(39)

## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
model_kwargs = {
	"layers": 4,
	"neurons": 4 * [6]
}

evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, model_kwargs=model_kwargs, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
12,1.323,6.458,0.338,12.0,28.0,238.0,3.0,0.0,7,-0.000000
1,2.344,4.479,0.616,76.0,30.0,70.0,3.0,1.0,17,0.013958
11,2.344,4.479,0.616,36.0,21.0,62.0,3.0,1.0,7,0.015296
18,1.828,5.384,0.464,44.0,37.0,291.0,3.0,0.0,9,0.015369
38,2.344,4.479,0.616,76.0,30.0,221.0,3.0,0.0,14,0.016542
32,1.897,2.628,0.221,57.0,10.0,83.0,3.0,0.0,14,0.035994
42,1.828,2.488,0.257,46.0,42.0,113.0,3.0,0.0,19,0.039009
36,7.218,8.254,0.673,98.0,17.0,564.0,3.0,1.0,12,0.040995
27,4.383,2.628,0.221,57.0,10.0,83.0,3.0,1.0,6,0.051997
31,1.897,2.628,0.221,57.0,30.0,83.0,3.0,1.0,18,0.059702
40,1.023,4.479,0.643,78.0,10.0,466.0,2.0,0.0,19,0.068719
2,2.344,4.479,0.616,85.0,24.0,62.0,3.0,1.0,16,0.074289
3,1.897,2.628,0.221,57.0,10.0,703.0,3.0,1.0,8,0.075062
48,3.414,5.176,0.725,79.0,50.0,18.0,3.0,0.0,9,0.101356
9,1.828,4.042,0.342,46.0,30.0,150.0,3.0,1.0,17,0.117236
28,1.897,2.628,0.221,82.0,10.0,83.0,3.0,1.0,15,0.118745
39,1.828,4.505,0.464,85.0,37.0,113.0,3.0,1.0,17,0.121230
0,2.344,4.479,0.616,76.0,30.0,293.0,3.0,1.0,18,0.128430
17,7.628,4.479,0.616,36.0,21.0,62.0,3.0,1.0,17,0.161867
24,4.553,4.479,0.345,36.0,25.0,13.0,3.0,1.0,15,0.163066
6,1.897,2.628,0.221,57.0,10.0,83.0,3.0,1.0,3,0.167934
10,2.344,4.479,0.616,76.0,30.0,221.0,3.0,1.0,10,0.194056
23,3.414,9.022,0.246,49.0,13.0,539.0,3.0,1.0,6,0.205495
13,1.828,2.488,0.397,46.0,37.0,113.0,3.0,0.0,15,0.265757
45,1.023,4.479,0.643,78.0,32.0,466.0,3.0,0.0,13,0.272608
21,1.828,6.644,0.467,46.0,12.0,234.0,3.0,0.0,15,0.284056
7,1.323,4.256,0.338,43.0,47.0,274.0,3.0,1.0,12,0.288918
44,1.323,4.256,0.338,43.0,47.0,274.0,3.0,0.0,6,0.311033
37,1.323,4.256,0.611,43.0,14.0,274.0,3.0,0.0,18,0.323925
43,1.323,4.256,0.338,43.0,47.0,288.0,3.0,0.0,9,0.334344
29,1.828,2.488,0.257,46.0,37.0,113.0,3.0,0.0,13,0.344045
4,5.780,9.022,0.426,27.0,17.0,43.0,3.0,0.0,12,0.366769
8,1.828,6.644,0.513,46.0,37.0,234.0,3.0,0.0,3,0.367396
14,3.806,2.628,0.221,57.0,13.0,83.0,3.0,1.0,8,0.376688
19,1.323,4.256,0.338,95.0,28.0,238.0,3.0,0.0,9,0.386020
49,2.344,4.479,0.616,76.0,30.0,13.0,3.0,1.0,5,0.406054
47,1.023,4.479,0.643,78.0,10.0,466.0,3.0,0.0,16,0.408013
20,1.828,2.488,0.464,46.0,37.0,113.0,3.0,0.0,3,0.419143
30,1.323,4.256,0.338,43.0,14.0,274.0,3.0,0.0,14,0.461782
35,1.323,4.256,0.744,43.0,47.0,274.0,3.0,1.0,15,0.462993
34,5.187,9.405,0.221,57.0,10.0,83.0,3.0,1.0,6,0.495303
26,2.344,4.479,0.616,88.0,21.0,62.0,3.0,1.0,18,0.520841
41,5.780,9.022,0.426,27.0,10.0,43.0,3.0,0.0,6,0.525678
25,3.806,2.994,0.221,57.0,10.0,83.0,3.0,1.0,10,0.587341
16,1.467,8.254,0.673,98.0,27.0,390.0,3.0,1.0,2,0.625972
33,2.344,4.479,0.616,76.0,30.0,179.0,3.0,0.0,17,0.660271
46,4.383,2.628,0.221,57.0,30.0,83.0,3.0,1.0,19,0.733917
15,1.828,6.644,0.467,46.0,37.0,234.0,3.0,0.0,10,0.751256
22,1.023,4.479,0.643,78.0,28.0,466.0,3.0,0.0,18,0.774541
5,1.323,4.256,0.338,95.0,28.0,459.0,3.0,0.0,18,0.809349

In [10]:
SEED = evotoon.make_seed(346)

## EXAMPLE WITH AntKnapsackClean-Master

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("alpha", 1.0, 10.0, 3),
	FloatParam("beta", 1.0, 10.0, 3),	
	FloatParam("rho", 0.1, 1.0, 3),
]
int_params = [
	IntParam("ants", 5, 100),
	IntParam("nnls", 5, 50),
	IntParam("elitistants", 1, 750)
]
cat_params = [
	CatParam("localsearch", [0,1,2,3]),
	CatParam("dlb", [0,1])
]
all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}

initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
#path = "./ALL_tsp"
n = 1
m = 100

#instance_list = evotoon.choose_instances(path, n , SEED)

instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]


instance_list, seed_list = evotoon.select_seeds(instance_list, m, SEED)
optimal_list = [optimal_solutions[instance[:-4].split("/")[-1]] for instance in instance_list]
# print(separator, "Instances running and seeds", separator)
# for ins, seed, optimal in zip(instance_list,seed_list, optimal_list):
# 	print("instance:", ins, "seed:", seed, "optimal", optimal)

function_kwargs = {
	"executable_path": "./ACOTSP-master/acotsp",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"optimal_list": optimal_list,
}
model_kwargs = {
	"layers": 4,
	"neurons": 4 * [6]
}

evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_ACOTSP, model_kwargs=model_kwargs, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

WARNING:tensorflow:5 out of the last 9 calls to <function PreprocessingLayer.make_adapt_function.<locals>.adapt_step at 0x168bdb160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

,alpha,beta,rho,ants,nnls,elitistants,localsearch,dlb,Step_Found,VALUE
38,1.949,9.995,0.219,59.0,47.0,669.0,3.0,1.0,19,-0.000000
22,2.054,8.670,0.162,20.0,49.0,528.0,3.0,0.0,5,-0.000000
9,1.542,7.654,0.405,29.0,26.0,708.0,3.0,1.0,11,0.019454
23,2.699,7.904,0.339,64.0,36.0,279.0,3.0,1.0,4,0.021563
36,1.955,6.880,0.133,51.0,26.0,427.0,3.0,0.0,5,0.029503
43,1.542,8.833,0.405,29.0,50.0,708.0,3.0,1.0,18,0.030590
47,1.949,9.995,0.405,51.0,11.0,669.0,3.0,0.0,11,0.039561
28,2.259,9.985,0.261,51.0,26.0,101.0,3.0,0.0,18,0.042455
27,1.955,4.780,0.133,51.0,24.0,642.0,3.0,1.0,14,0.048016
39,2.500,2.674,0.788,88.0,41.0,162.0,3.0,1.0,19,0.053549
5,2.033,9.144,0.674,95.0,30.0,708.0,3.0,1.0,13,0.054469
31,2.259,9.985,0.405,51.0,26.0,101.0,3.0,0.0,8,0.057743
20,3.112,7.178,0.750,76.0,27.0,98.0,3.0,1.0,17,0.067107
3,7.487,6.246,0.250,83.0,41.0,105.0,3.0,1.0,9,0.072539
44,1.955,4.539,0.133,51.0,47.0,427.0,3.0,1.0,17,0.098900
7,6.161,7.994,0.699,63.0,39.0,110.0,3.0,1.0,19,0.148498
41,3.744,7.994,0.699,63.0,38.0,110.0,3.0,1.0,18,0.151902
4,2.500,6.490,0.524,88.0,15.0,616.0,3.0,1.0,12,0.152833
40,2.033,9.144,0.674,95.0,30.0,708.0,2.0,1.0,17,0.157593
16,2.699,7.904,0.339,64.0,36.0,610.0,3.0,1.0,17,0.180318
10,6.020,1.134,0.133,51.0,26.0,642.0,3.0,0.0,12,0.183591
17,1.895,7.102,0.605,88.0,33.0,105.0,3.0,1.0,17,0.183845
30,3.112,7.178,0.198,76.0,19.0,317.0,3.0,1.0,13,0.196336
15,2.033,5.976,0.601,37.0,19.0,708.0,3.0,1.0,1,0.198738
29,2.699,7.904,0.534,64.0,36.0,578.0,3.0,1.0,19,0.207654
6,2.259,9.985,0.490,51.0,26.0,343.0,3.0,0.0,14,0.222821
11,3.381,7.976,0.333,76.0,19.0,317.0,3.0,1.0,15,0.229009
34,4.566,7.904,0.340,64.0,14.0,279.0,3.0,0.0,3,0.247480
14,2.500,6.490,0.431,41.0,15.0,393.0,3.0,1.0,15,0.247902
21,2.054,9.972,0.162,89.0,49.0,528.0,3.0,0.0,14,0.265458
18,1.949,9.995,0.405,59.0,47.0,669.0,3.0,0.0,17,0.289410
24,1.955,4.539,0.209,51.0,47.0,427.0,3.0,1.0,18,0.330390
19,1.955,4.539,0.133,51.0,26.0,427.0,3.0,1.0,10,0.330874
8,1.955,4.890,0.133,51.0,26.0,427.0,3.0,1.0,17,0.339305
1,3.381,7.976,0.198,76.0,19.0,317.0,3.0,1.0,12,0.344364
35,8.953,1.756,0.339,64.0,36.0,446.0,3.0,1.0,18,0.344859
48,1.949,9.985,0.313,48.0,26.0,669.0,3.0,0.0,18,0.399621
32,1.955,4.780,0.133,51.0,24.0,642.0,3.0,0.0,10,0.416121
49,1.955,7.509,0.209,51.0,47.0,427.0,3.0,1.0,19,0.445861
45,1.949,9.985,0.835,48.0,26.0,669.0,3.0,0.0,19,0.447467
2,8.667,3.081,0.336,73.0,30.0,708.0,3.0,1.0,19,0.460429
37,2.033,5.976,0.303,37.0,10.0,708.0,3.0,0.0,19,0.481919
42,1.895,9.440,0.312,88.0,15.0,105.0,3.0,1.0,8,0.496500
0,1.895,4.148,0.605,88.0,15.0,105.0,3.0,1.0,17,0.503190
13,2.500,5.204,0.524,88.0,40.0,616.0,3.0,1.0,16,0.508365
26,1.680,1.601,0.968,57.0,19.0,736.0,3.0,0.0,17,0.535258
46,1.955,1.208,0.133,51.0,27.0,427.0,3.0,1.0,19,0.552347
25,2.500,2.674,0.312,88.0,41.0,616.0,3.0,1.0,10,0.561826
12,1.955,1.208,0.133,51.0,26.0,427.0,3.0,1.0,18,0.625214
33,1.955,6.880,0.133,51.0,26.0,427.0,3.0,1.0,14,0.634502

In [11]:
print("XD")

XD