In [5]:
## IMPORTS 
import evotoon
from data_classes import CatParam, IntParam, FloatParam


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#import seaborn as sns#

import random

In [6]:
## MAKE SEED
SEED = evotoon.make_seed(39)
separator = "--------------------------------------------------------"

In [7]:
## EXAMPLE WITH CodGA

# Env configuration
poblation_size = 10

# Parameter settings
float_params = [
	FloatParam("p_c", 0.0001, 0.1, 4),
	FloatParam("p_m", 0.0001, 0.1, 4),
]
int_params = [
	IntParam("N", 1, 50),
	IntParam("t_max", 100, 10000),
]
cat_params = [
	CatParam("c_0", [1, 2]),
]


all_params = float_params + int_params + cat_params
all_params = {param.name: param for param in all_params}



initial_batch = evotoon.initialization(poblation_size, float_params, int_params, cat_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
path = "./InstanciasNKLandscapes/Instances-Testing"
n = 1

instance_list = evotoon.choose_instances(path, n , SEED)
instance_list, seed_list = evotoon.select_seeds(instance_list, 3, SEED)
print(separator, "Instances running and seeds", separator)
for ins,seed in zip(instance_list,seed_list):
	print("instance:", ins, "seed:", seed)

function_kwargs = {
	"executable_path": "./CodGA/ga-nk",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"output": "xd.txt"
}

print(pd.DataFrame(initial_batch))

-------------------------------------------------------- Instances running and seeds --------------------------------------------------------
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_20/nk_20_2.753 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_20/nk_20_2.753 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_20/nk_20_2.753 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_38/nk_38_2.262 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_38/nk_38_2.262 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_38/nk_38_2.262 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_52/nk_52_2.982 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_52/nk_52_2.982 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_2_52/nk_52_2.982 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_20/nk_20_3.85 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_20/nk_20_3.85 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_20/nk_20_3.85 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_34/nk_34_3.122 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_34/nk_34_3.122 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_34/nk_34_3.122 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_48/nk_48_3.37 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_48/nk_48_3.37 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_3_48/nk_48_3.37 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_20/nk_20_4.72 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_20/nk_20_4.72 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_20/nk_20_4.72 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_30/nk_30_4.911 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_30/nk_30_4.911 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_30/nk_30_4.911 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_40/nk_40_4.88 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_40/nk_40_4.88 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_4_40/nk_40_4.88 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_20/nk_20_5.166 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_20/nk_20_5.166 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_20/nk_20_5.166 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_28/nk_28_5.436 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_28/nk_28_5.436 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_28/nk_28_5.436 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_38/nk_38_5.105 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_38/nk_38_5.105 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_5_38/nk_38_5.105 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_20/nk_20_6.198 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_20/nk_20_6.198 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_20/nk_20_6.198 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_26/nk_26_6.49 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_26/nk_26_6.49 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_26/nk_26_6.49 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_32/nk_32_6.419 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_32/nk_32_6.419 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Testing/nk_6_32/nk_32_6.419 seed: 41
      p_c     p_m   N  t_max  c_0
0  0.0312  0.0238  20   1603    1
1  0.0282  0.0529  43   8122    2
2  0.0747  0.0985  15    681    2
3  0.0646  0.0469  26   6279    1
4  0.0552  0.0710  38   5412    1
5  0.0863  0.0135  46   4525    1
6  0.0055  0.0336   9   9468    2
7  0.0992  0.0025  11   3762    1
8  0.0460  0.0692   1   7354    2
9  0.0180  0.0824  33   3060    2

In [8]:
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, cat_params=cat_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_CodGA, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

4550

/usr/local/lib/python3.8/site-packages/scipy/stats/stats.py:7975: RuntimeWarning: invalid value encountered in double_scalars
  chisq = (12.0 / (k*n*(k+1)) * ssbn - 3*n*(k+1)) / c

4100

/usr/local/lib/python3.8/site-packages/scipy/stats/stats.py:7975: RuntimeWarning: invalid value encountered in double_scalars
  chisq = (12.0 / (k*n*(k+1)) * ssbn - 3*n*(k+1)) / c

3650

/usr/local/lib/python3.8/site-packages/scipy/stats/stats.py:7975: RuntimeWarning: invalid value encountered in double_scalars
  chisq = (12.0 / (k*n*(k+1)) * ssbn - 3*n*(k+1)) / c

3200

/usr/local/lib/python3.8/site-packages/scipy/stats/stats.py:7975: RuntimeWarning: invalid value encountered in double_scalars
  chisq = (12.0 / (k*n*(k+1)) * ssbn - 3*n*(k+1)) / c

2750
2300
1850
1400
950
500
50

      p_c     p_m     N   t_max  c_0  VALUE
0  0.0312  0.0238  20.0  1603.0  1.0  100.0
1  0.0282  0.0529  43.0  8122.0  2.0  100.0
2  0.0747  0.0985  15.0   681.0  2.0  100.0
3  0.0646  0.0469  26.0  6279.0  1.0  100.0
4  0.0552  0.0710  38.0  5412.0  1.0  100.0
5  0.0863  0.0135  46.0  4525.0  1.0  100.0
6  0.0055  0.0336   9.0  9468.0  2.0  100.0
7  0.0992  0.0025  11.0  3762.0  1.0  100.0
8  0.0460  0.0692   1.0  7354.0  2.0  100.0
9  0.0180  0.0824  33.0  3060.0  2.0  100.0

In [5]:
./CodGA/ga-nk ./InstanciasNKLandscapes/Instances-Testing/nk_3_20/nk_20_3.85 xd.txt 0.0312 0.0238 49.0 618.0 39 1.0

      p_c     p_m   N  t_max  c_0
0  0.0312  0.0238  49    568    1
1  0.0282  0.0529  83    101    2
2  0.0747  0.0985  30    810    2
3  0.0646  0.0469  53     70    1
4  0.0552  0.0710  77    674    1
5  0.0863  0.0135  91    352    1
6  0.0055  0.0336  19    939    2
7  0.0992  0.0025  28    481    1
8  0.0460  0.0692   9    284    2
9  0.0180  0.0824  63    798    2