In [3]:
## IMPORTS 
import evotoon
from data_classes import CatParam, IntParam, FloatParam

import numpy as np
import pandas as pd

import random

In [4]:
## MAKE SEED
SEED = evotoon.make_seed(765)
separator = "--------------------------------------------------------"

In [11]:
def choose_instances(path: str, n: int, seed: int):
    instance_list = []
    tsp = False
    for file in sorted(os.listdir(path)):
        file_path = os.path.join(path, file)
        if os.path.isdir(file_path):
            if file != ".DS_Store":
                instances = sorted(os.listdir(file_path))
                instances = [os.path.join(path, file, ins) for ins in instances]
                instance_list += instances #random.sample(instances, n)
                
        elif file.endswith(".tsp"):
            tsp = True
            instance_list.append(path + "/" + file)
    if tsp:
        instance_list = random.sample(instance_list, n)
    return instance_list

In [73]:
folder_list = [
		'./InstanciasNKLandscapes/Instances-Testing/nk_2_20',
		'./InstanciasNKLandscapes/Instances-Testing/nk_2_38',
		'./InstanciasNKLandscapes/Instances-Testing/nk_2_52',
		'./InstanciasNKLandscapes/Instances-Testing/nk_3_20',
		'./InstanciasNKLandscapes/Instances-Testing/nk_3_34',
		'./InstanciasNKLandscapes/Instances-Testing/nk_3_48',
		'./InstanciasNKLandscapes/Instances-Testing/nk_4_20',
		'./InstanciasNKLandscapes/Instances-Testing/nk_4_30',
		'./InstanciasNKLandscapes/Instances-Testing/nk_4_40',
		'./InstanciasNKLandscapes/Instances-Testing/nk_5_20',
		'./InstanciasNKLandscapes/Instances-Testing/nk_5_28',
		'./InstanciasNKLandscapes/Instances-Testing/nk_5_38',
		'./InstanciasNKLandscapes/Instances-Testing/nk_6_20',
		'./InstanciasNKLandscapes/Instances-Testing/nk_6_26',
		'./InstanciasNKLandscapes/Instances-Testing/nk_6_32'
 ]

In [75]:
def run_ga(folder, seed):
	instance_list = []
	path = folder
	for file in sorted(os.listdir(path)):
		file_path = os.path.join(path, file)
		instance_list.append(file_path)

	p_c = 0.809
	p_m = 0.186
	N = 42
	t_max = 100000
	output = "lol.txt"

	f = open("./codgatesting/"+folder.split("/")[-1]+"-"+str(seed)+".txt", "a")
	for file in instance_list:
		out = evotoon.execute_CodGA(file, seed, "./CodGA/ga-nk", p_c, p_m, N, t_max, output) * -1
		f.write(str(out)+"\n")
	f.close()

In [76]:
for i in range(SEED, SEED + 5):
	for folder in folder_list:
		run_ga(folder, i)

In [5]:
optimal_solutions = {
	"a280" : 2579,
	"ali535" : 202339,
	"att48" : 10628,
	"att532" : 27686,
	"bayg29" : 1610,
	"bays29" : 2020,
	"berlin52" : 7542,
	"bier127" : 118282,
	"brazil58" : 25395,
	"brd14051" : 469385,
	"brg180" : 1950,
	"burma14" : 3323,
	"ch130" : 6110,
	"ch150" : 6528,
	"d198" : 15780,
	"d493" : 35002,
	"d657" : 48912,
	"d1291" : 50801,
	"d1655" : 62128,
	"d2103" : 80450,
	"d15112" : 1573084,
	"d18512" : 645238,
	"dantzig42" : 699,
	"dsj1000" : 18659688, 
	"dsj1000" : 18660188,
	"eil51" : 426,
	"eil76" : 538,
	"eil101" : 629,
	"fl417" : 11861,
	"fl1400" : 20127,
	"fl1577" : 22249,
	"fl3795" : 28772,
	"fnl4461" : 182566,
	"fri26" : 937,
	"gil262" : 2378,
	"gr17" : 2085,
	"gr21" : 2707,
	"gr24" : 1272,
	"gr48" : 5046,
	"gr96" : 55209,
	"gr120" : 6942,
	"gr137" : 69853,
	"gr202" : 40160,
	"gr229" : 134602,
	"gr431" : 171414,
	"gr666" : 294358,
	"hk48" : 11461,
	"kroA100" : 21282,
	"kroB100" : 22141,
	"kroC100" : 20749,
	"kroD100" : 21294,
	"kroE100" : 22068,
	"kroA150" : 26524,
	"kroB150" : 26130,
	"kroA200" : 29368,
	"kroB200" : 29437,
	"lin105" : 14379,
	"lin318" : 42029,
	"linhp318" : 41345,
	"nrw1379" : 56638,
	"p654" : 34643,
	"pa561" : 2763,
	"pcb442" : 50778,
	"pcb1173" : 56892,
	"pcb3038" : 137694,
	"pla7397" : 23260728,
	"pla33810" : 66048945,
	"pla85900" : 142382641,
	"pr76" : 108159,
	"pr107" : 44303,
	"pr124" : 59030,
	"pr136" : 96772,
	"pr144" : 58537,
	"pr152" : 73682,
	"pr226" : 80369,
	"pr264" : 49135,
	"pr299" : 48191,
	"pr439" : 107217,
	"pr1002" : 259045,
	"pr2392" : 378032,
	"rat99" : 1211,
	"rat195" : 2323,
	"rat575" : 6773,
	"rat783" : 8806,
	"rd100" : 7910,
	"rd400" : 15281,
	"rl1304" : 252948,
	"rl1323" : 270199,
	"rl1889" : 316536,
	"rl5915" : 565530,
	"rl5934" : 556045,
	"rl11849" : 923288,
	"si175" : 21407,
	"si535" : 48450,
	"si1032" : 92650,
	"st70" : 675,
	"swiss42" : 1273,
	"ts225" : 126643,
	"tsp225" : 3916,
	"u159" : 42080,
	"u574" : 36905,
	"u724" : 41910,
	"u1060" : 224094,
	"u1432" : 152970,
	"u1817" : 57201,
	"u2152" : 64253,
	"u2319" : 234256,
	"ulysses16" : 6859,
	"ulysses22" : 7013,
	"usa13509" : 19982859,
	"vm1084" : 239297,
	"vm1748" : 336556,
}

In [6]:
def run_acotsp(seed):
	alpha = 2.012
	beta =  7.034
	rho =  0.206
	ants = 25
	nnls = 19
	elitistants = 245
	localsearch = 1
	dlb = 1

	instance_list = [
		"./ALL_tsp/a280.tsp",
		"./ALL_tsp/ali535.tsp",
		"./ALL_tsp/att48.tsp",
		"./ALL_tsp/d1655.tsp",
		"./ALL_tsp/eil101.tsp",
		"./ALL_tsp/eil51.tsp",
		"./ALL_tsp/gr202.tsp",
		"./ALL_tsp/gr229.tsp",
		"./ALL_tsp/gr431.tsp",
		"./ALL_tsp/gr666.tsp",
		"./ALL_tsp/kroA150.tsp",
		"./ALL_tsp/kroB100.tsp",
		"./ALL_tsp/kroB150.tsp",
		"./ALL_tsp/kroB200.tsp",
		"./ALL_tsp/p654.tsp",
		"./ALL_tsp/pcb1173.tsp",
		"./ALL_tsp/pr124.tsp",
		"./ALL_tsp/pr136.tsp",
		"./ALL_tsp/pr264.tsp",
		"./ALL_tsp/pr76.tsp",
		"./ALL_tsp/rat575.tsp",
		"./ALL_tsp/rat99.tsp",
		"./ALL_tsp/rd100.tsp",
		"./ALL_tsp/rl1304.tsp",
		"./ALL_tsp/rl1323.tsp",
		"./ALL_tsp/u1432.tsp",
		"./ALL_tsp/vm1748.tsp",
	]
	
	for file in instance_list:
		f_name = file.split("/")[-1].split(".")[0]
		f = open("./acotsptesting/"+f_name+"-"+str(seed)+".txt", "a")
		try:
			out = evotoon.execute_ACOTSP(file, seed, optimal_solutions[f_name], "./ACOTSP-master/acotsp", alpha, beta, rho, ants, nnls, elitistants, localsearch, dlb) * -1
		except:
			out = str((file, seed, optimal_solutions[f_name], "./ACOTSP-master/acotsp", alpha, beta, rho, ants, nnls, elitistants, localsearch, dlb))
		f.write(str(out)+"\n")
		f.close()

In [7]:
for i in range(SEED, SEED + 5):
	run_acotsp(i)

./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/a280.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 2579
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/ali535.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 202339
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/att48.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 10628
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/d1655.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 62128
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil101.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 629
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil51.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 426
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr202.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 40160
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr229.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 134602
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr431.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 171414
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr666.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 294358
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroA150.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26524
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB100.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 22141
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB150.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26130
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB200.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 29437
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/p654.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 34643
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pcb1173.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 56892
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr124.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 59030
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr136.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 96772
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr264.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 49135
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr76.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 108159
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rat575.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 6773
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rat99.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 1211
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rd100.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 7910
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rl1304.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 252948
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rl1323.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 270199
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/u1432.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 152970
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/vm1748.tsp --eas --seed 765 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 336556
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/a280.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 2579
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/ali535.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 202339
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/att48.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 10628
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/d1655.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 62128
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil101.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 629
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil51.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 426
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr202.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 40160
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr229.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 134602
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr431.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 171414
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr666.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 294358
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroA150.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26524
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB100.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 22141
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB150.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26130
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB200.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 29437
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/p654.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 34643
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pcb1173.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 56892
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr124.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 59030
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr136.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 96772
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr264.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 49135
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr76.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 108159
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rat575.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 6773
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rat99.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 1211
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rd100.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 7910
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rl1304.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 252948
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rl1323.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 270199
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/u1432.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 152970
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/vm1748.tsp --eas --seed 766 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 336556
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/a280.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 2579
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/ali535.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 202339
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/att48.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 10628
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/d1655.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 62128
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil101.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 629
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil51.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 426
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr202.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 40160
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr229.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 134602
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr431.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 171414
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr666.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 294358
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroA150.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26524
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB100.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 22141
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB150.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26130
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB200.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 29437
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/p654.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 34643
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pcb1173.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 56892
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr124.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 59030
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr136.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 96772
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr264.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 49135
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr76.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 108159
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rat575.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 6773
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rat99.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 1211
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rd100.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 7910
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rl1304.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 252948
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rl1323.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 270199
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/u1432.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 152970
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/vm1748.tsp --eas --seed 767 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 336556
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/a280.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 2579
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/ali535.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 202339
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/att48.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 10628
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/d1655.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 62128
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil101.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 629
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/eil51.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 426
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr202.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 40160
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr229.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 134602
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr431.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 171414
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/gr666.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 294358
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroA150.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26524
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB100.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 22141
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB150.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 26130
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/kroB200.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 29437
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/p654.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 34643
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pcb1173.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 56892
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr124.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 59030
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr136.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 96772
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr264.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 49135
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/pr76.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 108159
./ACOTSP-master/acotsp --tsplibfile ./ALL_tsp/rat575.tsp --eas --seed 768 --tours 50 --time 5 --alpha 2.012 --beta 7.034 --rho 0.206 --nnls 19 --ants 25 --elitistants 245 --dlb 1 --optimum 6773

In [39]:
path = "./codgatesting/"
cols = ["SEED " + str(i) for i in range(SEED, SEED+5)]
dict_y = {}

for file in sorted(os.listdir(path)):
	file_path = os.path.join(path, file)
	f = open(file_path, "r")
	lines = f.readlines()
	lines = [float(line.rstrip("\n")) for line in lines]
	mean = sum(lines)/len(lines)
	row_name, seed = file.split("-")[0], file.split("-")[1].split(".")[0]
	if not dict_y.get(row_name):
		dict_y[row_name] = {}
	dict_y[row_name][seed] = mean
	f.close()

df = pd.DataFrame.from_dict(dict_y, orient='index')
df.loc["Promedio"] = df.mean()
df.loc["Mediana"] = df.median()
df.loc["Desviación"] = df.std()
df.round(1)

              765    766    767    768    769
nk_2_20       7.7    8.4    8.5    8.5    8.5
nk_2_38      50.8   52.2   50.5   50.1   47.4
nk_2_52     200.8  195.5  199.6  236.0  211.1
nk_3_20      16.7   17.3   17.4   16.0   16.3
nk_3_34      88.6   86.8   90.0   89.4   86.8
nk_3_48     438.2  422.0  448.9  476.5  488.9
nk_4_20      31.4   34.6   28.8   30.6   30.6
nk_4_30     122.7  118.3  121.1  121.2  129.4
nk_4_40     447.8  448.3  457.5  471.2  434.6
nk_5_20      53.6   56.6   54.3   54.7   55.8
nk_5_28     181.9  182.5  192.0  187.7  182.2
nk_5_38     826.7  821.2  816.2  802.1  841.8
nk_6_20      98.5  101.8   94.7  103.1   91.2
nk_6_26     268.5  276.3  293.2  271.2  278.3
nk_6_32     726.9  721.8  806.1  785.9  779.6
Promedio    237.4  236.2  245.3  246.9  245.5
Mediana     152.3  150.4  156.6  154.5  155.8
Desviación  243.8  241.3  254.1  251.0  255.2

In [42]:
path = "./acotsptesting/"
cols = ["SEED " + str(i) for i in range(SEED, SEED+5)]
dict_y = {}

for file in sorted(os.listdir(path)):
	file_path = os.path.join(path, file)
	f = open(file_path, "r")
	lines = f.readlines()
	lines = [float(line.rstrip("\n")) for line in lines]
	mean = sum(lines)/len(lines)
	row_name, seed = file.split("-")[0], file.split("-")[1].split(".")[0]
	if not dict_y.get(row_name):
		dict_y[row_name] = {}
	dict_y[row_name][seed] = mean
	f.close()

df = pd.DataFrame.from_dict(dict_y, orient='index')
df.loc["Promedio"] = df.mean()
df.loc["Mediana"] = df.median()
df.loc["Desviación"] = df.std()
df.round(3)

              765    766    767    768    769
a280        0.000  0.000  0.000  0.000  0.000
ali535      0.000  0.000  0.000  0.000  0.000
att48       0.000  0.000  0.000  0.000  0.000
d1655       0.468  0.596  1.103  0.505  0.736
eil101      0.000  0.000  0.000  0.000  0.000
eil51       0.000  0.000  0.000  0.000  0.000
gr202       0.000  0.000  0.000  0.000  0.000
gr229       0.010  0.000  0.000  0.000  0.000
gr431       0.000  0.000  0.000  0.000  0.000
gr666       0.000  0.015  0.017  0.059  0.003
kroA150     0.000  0.000  0.000  0.000  0.000
kroB100     0.000  0.000  0.000  0.000  0.000
kroB150     0.000  0.000  0.000  0.000  0.000
kroB200     0.000  0.000  0.000  0.000  0.000
p654        0.035  0.052  0.035  0.052  0.017
pcb1173     0.032  0.257  0.070  0.009  0.107
pr124       0.000  0.000  0.000  0.000  0.000
pr136       0.000  0.000  0.000  0.000  0.000
pr264       0.000  0.000  0.000  0.000  0.000
pr76        0.000  0.000  0.000  0.000  0.000
rat575      0.221  0.192  0.162  0.089  0.177
rat99       0.000  0.000  0.000  0.000  0.000
rd100       0.000  0.000  0.000  0.000  0.000
rl1304      0.151  0.123  0.211  0.274  0.270
rl1323      0.159  0.187  0.182  0.245  0.041
u1432       0.464  0.597  0.677  0.773  0.741
vm1748      1.195  1.342  1.252  0.961  0.827
Promedio    0.101  0.124  0.137  0.110  0.108
Mediana     0.000  0.000  0.000  0.000  0.000
Desviación  0.246  0.284  0.320  0.240  0.238